@startuml
'https://plantuml.com/sequence-diagram

skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor #305680
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}

autonumber


DefaultActorService -> (ActorRef)AppActor: tellWithHighPriority(new AppInitMsg())

(ActorRef)AppActor -> TbActorMailBox: tellWithHighPriority

TbActorMailBox -> TbActorMailBox: enqueue

TbActorMailBox -> TbActorMailBox: tryProcessQueue

TbActorMailBox -> 

TbActorMailBox -> TbActorMailBox: processMailbox










' Alice -> Bob: Authentication Request
' activate Bob
' Bob --> Alice: Authentication Response
' deactivate Bob
' Alice -> Bob: Another authentication Request
' Alice <-- Bob: another authentication Response

' Alice -> Bob: naxx
' Alice <-- Bob: naxx





@enduml