@startuml

participant DefaultActorService as DefaultActorService
participant ActorSystemContext as ActorSystemContext
participant DefaultTbActorSystem as DefaultTbActorSystem
participant AppActor as AppActor
participant StatsActor as StatsActor

skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor #305680
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}

autonumber


DefaultActorService -> DefaultTbActorSystem: new

ActorSystemContext -> ActorSystemContext: setActorSystem(DefaultTbActorSystem)

DefaultTbActorSystem -> DefaultTbActorSystem: createRootActor

ActorSystemContext -> ActorSystemContext: setAppActor(ActorRef of AppActor)

DefaultTbActorSystem -> StatsActor: createRootActor

ActorSystemContext -> ActorSystemContext: setStatsActor(ActorRef of StatsActor)



' Alice -> Bob: Authentication Request
' activate Bob
' Bob --> Alice: Authentication Response
' deactivate Bob
' Alice -> Bob: Another authentication Request
' Alice <-- Bob: another authentication Response

' Alice -> Bob: naxx
' Alice <-- Bob: naxx





@enduml