@startuml


skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor #305680
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}

autonumber


MqttTransportHandler -> MqttTransportHandler: processMqttMsg
MqttTransportHandler -> MqttTransportHandler: processConnect
MqttTransportHandler -> MqttTransportHandler: processAuthTokenConnect
MqttTransportHandler -> DefaultTransportService: process
DefaultTransportService -> DefaultTransportService: doProcess
DefaultTransportService -> DefaultTbQueueRequestTemplate: send
DefaultTbQueueRequestTemplate -> TbQueueProducer: send
' DefaultTbQueueRequestTemplate -> InMemoryTbQueueProducer: send
' InMemoryTbQueueProducer -> TbQueueCallback: onSuccess
' DefaultTbQueueRequestTemplate -> TbKafkaProducerTemplate: send
' TbKafkaProducerTemplate -> KafkaProducer: send
...
DefaultTbQueueResponseTemplate -> TbQueueConsumer: poll
DefaultTbQueueResponseTemplate -> TbQueueProducer: send
...
DefaultTbQueueRequestTemplate -> TbQueueConsumer: poll
...
DefaultTransportService -> TransportServiceCallback: onSuccess
TransportServiceCallback -> MqttTransportHandler: onValidateDeviceResponse
MqttTransportHandler -> DefaultTransportService: process
DefaultTransportService -> DefaultTransportService: sendToDeviceActor
' DefaultTransportService -> InMemoryTbQueueProducer: send
' InMemoryTbQueueProducer -> StatsCallback: onSuccess
DefaultTransportService -> TbQueueProducer: send
StatsCallback -> TransportTbQueueCallback: onSuccess
TransportTbQueueCallback -> TransportServiceCallback: onSuccess
TransportServiceCallback -> ChannelHandlerContext: writeAndFlush

' Alice -> Bob: Authentication Request
' activate Bob
' Bob --> Alice: Authentication Response
' deactivate Bob
' Alice -> Bob: Another authentication Request
' Alice <-- Bob: another authentication Response

' Alice -> Bob: naxx
' Alice <-- Bob: naxx





@enduml